// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package libs

import (
	"github.com/kenta1234567893/upsider-coding-test/ent"
	"github.com/kenta1234567893/upsider-coding-test/src/controller"
	"github.com/kenta1234567893/upsider-coding-test/src/infra/repository"
	"github.com/kenta1234567893/upsider-coding-test/src/usecase/invoice"
)

// Injectors from wire.go:

func InitializeController(client *ent.Client) *InitializeControllers {
	invoiceRepository := repository.NewInvoiceRepository(client)
	createInvoiceUsecase := invoice.NewCreateInvoiceUsecase(invoiceRepository)
	invoiceController := controller.NewInvoiceController(createInvoiceUsecase)
	initializeControllers := &InitializeControllers{
		InvoiceController: invoiceController,
	}
	return initializeControllers
}

// wire.go:

type InitializeControllers struct {
	InvoiceController *controller.InvoiceController
}
