version: '3'
services:
  db:
    container_name: upsider-codingtest-db
    platform: linux/x86_64
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
    restart: always
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      MYSQL_DATABASE: common
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql_data:/var/lib/mysql
