// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kenta1234567893/upsider-coding-test/ent/customer"
	"github.com/kenta1234567893/upsider-coding-test/ent/customerbank"
	"github.com/kenta1234567893/upsider-coding-test/ent/predicate"
)

// CustomerBankQuery is the builder for querying CustomerBank entities.
type CustomerBankQuery struct {
	config
	ctx          *QueryContext
	order        []customerbank.OrderOption
	inters       []Interceptor
	predicates   []predicate.CustomerBank
	withCustomer *CustomerQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CustomerBankQuery builder.
func (cbq *CustomerBankQuery) Where(ps ...predicate.CustomerBank) *CustomerBankQuery {
	cbq.predicates = append(cbq.predicates, ps...)
	return cbq
}

// Limit the number of records to be returned by this query.
func (cbq *CustomerBankQuery) Limit(limit int) *CustomerBankQuery {
	cbq.ctx.Limit = &limit
	return cbq
}

// Offset to start from.
func (cbq *CustomerBankQuery) Offset(offset int) *CustomerBankQuery {
	cbq.ctx.Offset = &offset
	return cbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cbq *CustomerBankQuery) Unique(unique bool) *CustomerBankQuery {
	cbq.ctx.Unique = &unique
	return cbq
}

// Order specifies how the records should be ordered.
func (cbq *CustomerBankQuery) Order(o ...customerbank.OrderOption) *CustomerBankQuery {
	cbq.order = append(cbq.order, o...)
	return cbq
}

// QueryCustomer chains the current query on the "customer" edge.
func (cbq *CustomerBankQuery) QueryCustomer() *CustomerQuery {
	query := (&CustomerClient{config: cbq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cbq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(customerbank.Table, customerbank.FieldID, selector),
			sqlgraph.To(customer.Table, customer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, customerbank.CustomerTable, customerbank.CustomerColumn),
		)
		fromU = sqlgraph.SetNeighbors(cbq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CustomerBank entity from the query.
// Returns a *NotFoundError when no CustomerBank was found.
func (cbq *CustomerBankQuery) First(ctx context.Context) (*CustomerBank, error) {
	nodes, err := cbq.Limit(1).All(setContextOp(ctx, cbq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{customerbank.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cbq *CustomerBankQuery) FirstX(ctx context.Context) *CustomerBank {
	node, err := cbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CustomerBank ID from the query.
// Returns a *NotFoundError when no CustomerBank ID was found.
func (cbq *CustomerBankQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = cbq.Limit(1).IDs(setContextOp(ctx, cbq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{customerbank.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cbq *CustomerBankQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := cbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CustomerBank entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CustomerBank entity is found.
// Returns a *NotFoundError when no CustomerBank entities are found.
func (cbq *CustomerBankQuery) Only(ctx context.Context) (*CustomerBank, error) {
	nodes, err := cbq.Limit(2).All(setContextOp(ctx, cbq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{customerbank.Label}
	default:
		return nil, &NotSingularError{customerbank.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cbq *CustomerBankQuery) OnlyX(ctx context.Context) *CustomerBank {
	node, err := cbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CustomerBank ID in the query.
// Returns a *NotSingularError when more than one CustomerBank ID is found.
// Returns a *NotFoundError when no entities are found.
func (cbq *CustomerBankQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = cbq.Limit(2).IDs(setContextOp(ctx, cbq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{customerbank.Label}
	default:
		err = &NotSingularError{customerbank.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cbq *CustomerBankQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := cbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CustomerBanks.
func (cbq *CustomerBankQuery) All(ctx context.Context) ([]*CustomerBank, error) {
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryAll)
	if err := cbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CustomerBank, *CustomerBankQuery]()
	return withInterceptors[[]*CustomerBank](ctx, cbq, qr, cbq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cbq *CustomerBankQuery) AllX(ctx context.Context) []*CustomerBank {
	nodes, err := cbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CustomerBank IDs.
func (cbq *CustomerBankQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if cbq.ctx.Unique == nil && cbq.path != nil {
		cbq.Unique(true)
	}
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryIDs)
	if err = cbq.Select(customerbank.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cbq *CustomerBankQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := cbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cbq *CustomerBankQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryCount)
	if err := cbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cbq, querierCount[*CustomerBankQuery](), cbq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cbq *CustomerBankQuery) CountX(ctx context.Context) int {
	count, err := cbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cbq *CustomerBankQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cbq.ctx, ent.OpQueryExist)
	switch _, err := cbq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cbq *CustomerBankQuery) ExistX(ctx context.Context) bool {
	exist, err := cbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CustomerBankQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cbq *CustomerBankQuery) Clone() *CustomerBankQuery {
	if cbq == nil {
		return nil
	}
	return &CustomerBankQuery{
		config:       cbq.config,
		ctx:          cbq.ctx.Clone(),
		order:        append([]customerbank.OrderOption{}, cbq.order...),
		inters:       append([]Interceptor{}, cbq.inters...),
		predicates:   append([]predicate.CustomerBank{}, cbq.predicates...),
		withCustomer: cbq.withCustomer.Clone(),
		// clone intermediate query.
		sql:  cbq.sql.Clone(),
		path: cbq.path,
	}
}

// WithCustomer tells the query-builder to eager-load the nodes that are connected to
// the "customer" edge. The optional arguments are used to configure the query builder of the edge.
func (cbq *CustomerBankQuery) WithCustomer(opts ...func(*CustomerQuery)) *CustomerBankQuery {
	query := (&CustomerClient{config: cbq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cbq.withCustomer = query
	return cbq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CustomerBank.Query().
//		GroupBy(customerbank.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cbq *CustomerBankQuery) GroupBy(field string, fields ...string) *CustomerBankGroupBy {
	cbq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CustomerBankGroupBy{build: cbq}
	grbuild.flds = &cbq.ctx.Fields
	grbuild.label = customerbank.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CustomerBank.Query().
//		Select(customerbank.FieldCreatedAt).
//		Scan(ctx, &v)
func (cbq *CustomerBankQuery) Select(fields ...string) *CustomerBankSelect {
	cbq.ctx.Fields = append(cbq.ctx.Fields, fields...)
	sbuild := &CustomerBankSelect{CustomerBankQuery: cbq}
	sbuild.label = customerbank.Label
	sbuild.flds, sbuild.scan = &cbq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CustomerBankSelect configured with the given aggregations.
func (cbq *CustomerBankQuery) Aggregate(fns ...AggregateFunc) *CustomerBankSelect {
	return cbq.Select().Aggregate(fns...)
}

func (cbq *CustomerBankQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cbq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cbq); err != nil {
				return err
			}
		}
	}
	for _, f := range cbq.ctx.Fields {
		if !customerbank.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cbq.path != nil {
		prev, err := cbq.path(ctx)
		if err != nil {
			return err
		}
		cbq.sql = prev
	}
	return nil
}

func (cbq *CustomerBankQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CustomerBank, error) {
	var (
		nodes       = []*CustomerBank{}
		withFKs     = cbq.withFKs
		_spec       = cbq.querySpec()
		loadedTypes = [1]bool{
			cbq.withCustomer != nil,
		}
	)
	if cbq.withCustomer != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, customerbank.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CustomerBank).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CustomerBank{config: cbq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cbq.withCustomer; query != nil {
		if err := cbq.loadCustomer(ctx, query, nodes, nil,
			func(n *CustomerBank, e *Customer) { n.Edges.Customer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cbq *CustomerBankQuery) loadCustomer(ctx context.Context, query *CustomerQuery, nodes []*CustomerBank, init func(*CustomerBank), assign func(*CustomerBank, *Customer)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*CustomerBank)
	for i := range nodes {
		if nodes[i].customer_customer_banks == nil {
			continue
		}
		fk := *nodes[i].customer_customer_banks
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(customer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "customer_customer_banks" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cbq *CustomerBankQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cbq.querySpec()
	_spec.Node.Columns = cbq.ctx.Fields
	if len(cbq.ctx.Fields) > 0 {
		_spec.Unique = cbq.ctx.Unique != nil && *cbq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cbq.driver, _spec)
}

func (cbq *CustomerBankQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(customerbank.Table, customerbank.Columns, sqlgraph.NewFieldSpec(customerbank.FieldID, field.TypeUint64))
	_spec.From = cbq.sql
	if unique := cbq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cbq.path != nil {
		_spec.Unique = true
	}
	if fields := cbq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customerbank.FieldID)
		for i := range fields {
			if fields[i] != customerbank.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cbq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cbq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cbq *CustomerBankQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cbq.driver.Dialect())
	t1 := builder.Table(customerbank.Table)
	columns := cbq.ctx.Fields
	if len(columns) == 0 {
		columns = customerbank.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cbq.sql != nil {
		selector = cbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cbq.ctx.Unique != nil && *cbq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cbq.predicates {
		p(selector)
	}
	for _, p := range cbq.order {
		p(selector)
	}
	if offset := cbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CustomerBankGroupBy is the group-by builder for CustomerBank entities.
type CustomerBankGroupBy struct {
	selector
	build *CustomerBankQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cbgb *CustomerBankGroupBy) Aggregate(fns ...AggregateFunc) *CustomerBankGroupBy {
	cbgb.fns = append(cbgb.fns, fns...)
	return cbgb
}

// Scan applies the selector query and scans the result into the given value.
func (cbgb *CustomerBankGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cbgb.build.ctx, ent.OpQueryGroupBy)
	if err := cbgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomerBankQuery, *CustomerBankGroupBy](ctx, cbgb.build, cbgb, cbgb.build.inters, v)
}

func (cbgb *CustomerBankGroupBy) sqlScan(ctx context.Context, root *CustomerBankQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cbgb.fns))
	for _, fn := range cbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cbgb.flds)+len(cbgb.fns))
		for _, f := range *cbgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cbgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cbgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CustomerBankSelect is the builder for selecting fields of CustomerBank entities.
type CustomerBankSelect struct {
	*CustomerBankQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cbs *CustomerBankSelect) Aggregate(fns ...AggregateFunc) *CustomerBankSelect {
	cbs.fns = append(cbs.fns, fns...)
	return cbs
}

// Scan applies the selector query and scans the result into the given value.
func (cbs *CustomerBankSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cbs.ctx, ent.OpQuerySelect)
	if err := cbs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomerBankQuery, *CustomerBankSelect](ctx, cbs.CustomerBankQuery, cbs, cbs.inters, v)
}

func (cbs *CustomerBankSelect) sqlScan(ctx context.Context, root *CustomerBankQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cbs.fns))
	for _, fn := range cbs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cbs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
