// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kenta1234567893/upsider-coding-test/ent/company"
	"github.com/kenta1234567893/upsider-coding-test/ent/customer"
	"github.com/kenta1234567893/upsider-coding-test/ent/invoice"
)

// InvoiceCreate is the builder for creating a Invoice entity.
type InvoiceCreate struct {
	config
	mutation *InvoiceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ic *InvoiceCreate) SetCreatedAt(t time.Time) *InvoiceCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableCreatedAt(t *time.Time) *InvoiceCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updated_at" field.
func (ic *InvoiceCreate) SetUpdatedAt(t time.Time) *InvoiceCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ic *InvoiceCreate) SetNillableUpdatedAt(t *time.Time) *InvoiceCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// SetIssueDate sets the "issue_date" field.
func (ic *InvoiceCreate) SetIssueDate(t time.Time) *InvoiceCreate {
	ic.mutation.SetIssueDate(t)
	return ic
}

// SetPaymentAmount sets the "payment_amount" field.
func (ic *InvoiceCreate) SetPaymentAmount(f float64) *InvoiceCreate {
	ic.mutation.SetPaymentAmount(f)
	return ic
}

// SetFee sets the "fee" field.
func (ic *InvoiceCreate) SetFee(f float64) *InvoiceCreate {
	ic.mutation.SetFee(f)
	return ic
}

// SetFeeRate sets the "fee_rate" field.
func (ic *InvoiceCreate) SetFeeRate(f float64) *InvoiceCreate {
	ic.mutation.SetFeeRate(f)
	return ic
}

// SetTax sets the "tax" field.
func (ic *InvoiceCreate) SetTax(f float64) *InvoiceCreate {
	ic.mutation.SetTax(f)
	return ic
}

// SetTaxRate sets the "tax_rate" field.
func (ic *InvoiceCreate) SetTaxRate(f float64) *InvoiceCreate {
	ic.mutation.SetTaxRate(f)
	return ic
}

// SetBillingAmount sets the "billing_amount" field.
func (ic *InvoiceCreate) SetBillingAmount(f float64) *InvoiceCreate {
	ic.mutation.SetBillingAmount(f)
	return ic
}

// SetPaymentDueDate sets the "payment_due_date" field.
func (ic *InvoiceCreate) SetPaymentDueDate(t time.Time) *InvoiceCreate {
	ic.mutation.SetPaymentDueDate(t)
	return ic
}

// SetStatus sets the "status" field.
func (ic *InvoiceCreate) SetStatus(s string) *InvoiceCreate {
	ic.mutation.SetStatus(s)
	return ic
}

// SetID sets the "id" field.
func (ic *InvoiceCreate) SetID(u uint64) *InvoiceCreate {
	ic.mutation.SetID(u)
	return ic
}

// SetCompanyID sets the "company" edge to the Company entity by ID.
func (ic *InvoiceCreate) SetCompanyID(id uint64) *InvoiceCreate {
	ic.mutation.SetCompanyID(id)
	return ic
}

// SetCompany sets the "company" edge to the Company entity.
func (ic *InvoiceCreate) SetCompany(c *Company) *InvoiceCreate {
	return ic.SetCompanyID(c.ID)
}

// SetCustomerID sets the "customer" edge to the Customer entity by ID.
func (ic *InvoiceCreate) SetCustomerID(id uint64) *InvoiceCreate {
	ic.mutation.SetCustomerID(id)
	return ic
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (ic *InvoiceCreate) SetCustomer(c *Customer) *InvoiceCreate {
	return ic.SetCustomerID(c.ID)
}

// Mutation returns the InvoiceMutation object of the builder.
func (ic *InvoiceCreate) Mutation() *InvoiceMutation {
	return ic.mutation
}

// Save creates the Invoice in the database.
func (ic *InvoiceCreate) Save(ctx context.Context) (*Invoice, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InvoiceCreate) SaveX(ctx context.Context) *Invoice {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InvoiceCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InvoiceCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InvoiceCreate) defaults() {
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := invoice.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := invoice.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InvoiceCreate) check() error {
	if _, ok := ic.mutation.IssueDate(); !ok {
		return &ValidationError{Name: "issue_date", err: errors.New(`ent: missing required field "Invoice.issue_date"`)}
	}
	if _, ok := ic.mutation.PaymentAmount(); !ok {
		return &ValidationError{Name: "payment_amount", err: errors.New(`ent: missing required field "Invoice.payment_amount"`)}
	}
	if _, ok := ic.mutation.Fee(); !ok {
		return &ValidationError{Name: "fee", err: errors.New(`ent: missing required field "Invoice.fee"`)}
	}
	if _, ok := ic.mutation.FeeRate(); !ok {
		return &ValidationError{Name: "fee_rate", err: errors.New(`ent: missing required field "Invoice.fee_rate"`)}
	}
	if _, ok := ic.mutation.Tax(); !ok {
		return &ValidationError{Name: "tax", err: errors.New(`ent: missing required field "Invoice.tax"`)}
	}
	if _, ok := ic.mutation.TaxRate(); !ok {
		return &ValidationError{Name: "tax_rate", err: errors.New(`ent: missing required field "Invoice.tax_rate"`)}
	}
	if _, ok := ic.mutation.BillingAmount(); !ok {
		return &ValidationError{Name: "billing_amount", err: errors.New(`ent: missing required field "Invoice.billing_amount"`)}
	}
	if _, ok := ic.mutation.PaymentDueDate(); !ok {
		return &ValidationError{Name: "payment_due_date", err: errors.New(`ent: missing required field "Invoice.payment_due_date"`)}
	}
	if _, ok := ic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invoice.status"`)}
	}
	if len(ic.mutation.CompanyIDs()) == 0 {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required edge "Invoice.company"`)}
	}
	if len(ic.mutation.CustomerIDs()) == 0 {
		return &ValidationError{Name: "customer", err: errors.New(`ent: missing required edge "Invoice.customer"`)}
	}
	return nil
}

func (ic *InvoiceCreate) sqlSave(ctx context.Context) (*Invoice, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InvoiceCreate) createSpec() (*Invoice, *sqlgraph.CreateSpec) {
	var (
		_node = &Invoice{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(invoice.Table, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeUint64))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(invoice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ic.mutation.IssueDate(); ok {
		_spec.SetField(invoice.FieldIssueDate, field.TypeTime, value)
		_node.IssueDate = value
	}
	if value, ok := ic.mutation.PaymentAmount(); ok {
		_spec.SetField(invoice.FieldPaymentAmount, field.TypeFloat64, value)
		_node.PaymentAmount = value
	}
	if value, ok := ic.mutation.Fee(); ok {
		_spec.SetField(invoice.FieldFee, field.TypeFloat64, value)
		_node.Fee = value
	}
	if value, ok := ic.mutation.FeeRate(); ok {
		_spec.SetField(invoice.FieldFeeRate, field.TypeFloat64, value)
		_node.FeeRate = value
	}
	if value, ok := ic.mutation.Tax(); ok {
		_spec.SetField(invoice.FieldTax, field.TypeFloat64, value)
		_node.Tax = value
	}
	if value, ok := ic.mutation.TaxRate(); ok {
		_spec.SetField(invoice.FieldTaxRate, field.TypeFloat64, value)
		_node.TaxRate = value
	}
	if value, ok := ic.mutation.BillingAmount(); ok {
		_spec.SetField(invoice.FieldBillingAmount, field.TypeFloat64, value)
		_node.BillingAmount = value
	}
	if value, ok := ic.mutation.PaymentDueDate(); ok {
		_spec.SetField(invoice.FieldPaymentDueDate, field.TypeTime, value)
		_node.PaymentDueDate = value
	}
	if value, ok := ic.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := ic.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.CompanyTable,
			Columns: []string{invoice.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.company_invoices = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.CustomerTable,
			Columns: []string{invoice.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.customer_invoices = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InvoiceCreateBulk is the builder for creating many Invoice entities in bulk.
type InvoiceCreateBulk struct {
	config
	err      error
	builders []*InvoiceCreate
}

// Save creates the Invoice entities in the database.
func (icb *InvoiceCreateBulk) Save(ctx context.Context) ([]*Invoice, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Invoice, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InvoiceCreateBulk) SaveX(ctx context.Context) []*Invoice {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
